Added alive/dead check to singleping and updated README.md.

diff --git a/singleping b/singleping
--- a/singleping
+++ b/singleping
@@ -19,6 +19,18 @@ title() {
 	echo "#########################################################"
 	echo
 }
+
+is_alive() {
+	if ping -c 1 -W 1 $IP > /dev/null 2>&1; then
+		echo "$IP is alive, continuing...."
+		echo
+	else
+		echo "$IP is not responding to a ping, aborting...."
+		echo
+		exit 1
+	fi
+}
+
 outpath() {
 	if [ ! -d "$BASEDIR" ]; then
 		mkdir $BASEDIR
@@ -74,6 +86,7 @@ echo "Usage: singleping [X.X.X.X] where X.X.X.X is the IP to ping."
         echo
         exit 1
 fi
+is_alive
 outpath
 ping_ip
 stop_clean
